fix Incorrect timeout error when using FindStringMatch()
dlclark/regexp2 pull request #86
Opened 2024-08-21 09:14 UTC by Brinenas

fix Timeout Error issue: when the fastclock stop running, then next matches will get a wrong fast.current and daeline, thus trigger an incorrect timeout error.

2024-08-21 09:40 UTC, ccoVeille requested changes
LGTM 👍

but I would expect some tests to be provided with the fix. It would avoid errors in any future refactoring

2024-08-21 10:25 UTC, Brinenas commented
Add a new UT, If you comment the add code, the ut will failed.

2024-08-21 11:42 UTC, ccoVeille approved these changes

2024-08-21 11:42 UTC, ccoVeille commented on fastclock_test.go
> +		t.Errorf("Expectd current should bigger than %v, got %v", gotTick, nowTick)
Nitpicking, maybe this

```suggestion
		t.Errorf("Expectd current should greater than %v, got %v", gotTick, nowTick)
```

2024-08-21 12:09 UTC, ccoVeille approved these changes

2024-08-21 14:31 UTC, dlclark commented
Thanks for submitting this. Can you add an integration-level test showing the behavior fix from the API consumer perspective?

2024-08-22 02:35 UTC, Brinenas commented
Add a new UT for my own case. Maybe you guys can add a more elegant test.

2024-08-23 19:45 UTC, dlclark commented
@Brinenas a couple issues I see:
* `fast.running` and `fast.start` are protected by `fast.mu` for read/write, so we can't access them without getting the lock
* I don't think we want to get that lock every time we need to make a deadline because this is an edge case. I've refactored the code to only do this if we already know the deadline needs to be extended.

I did a couple other small tweaks to the test as well. Let me know if you see any issues with my change.

2024-12-31 19:52 UTC, merged

2025-02-11 11:58 UTC, bradrevans commented
This change fixed a similar issue for me - intermittent false timeouts seemingly triggered by a large volume of sequential regex matching that appeared after the inclusion of the fast clock back in v1.8.0. Appreciate theres probably a lot of other stuff on your plate but was wondering when we might be able to expect a new tagged release including this fix? Thanks for the effort on resolving this! <3

2025-02-11 18:18 UTC, dlclark commented
@bradrevans this is done.

2025-02-11 19:00 UTC, bradrevans commented
> @bradrevans this is done.

Ah. Thanks!